core/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from django.views.generic.base import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('jobs/',include('jobs.urls')),
    path('interviews/',include('interviews.urls')),
    path('',RedirectView.as_view(url='jobs/'))
]

interviews/urls.py
from django.urls import path
from .views import create,details,create_message

app_name = "interviews"

urlpatterns = [
    path("create/<int:job_pk>",create,name="create"),
    path("<uuid:uuid>/",details,name="details"),
    path("<uuid:chat_uuid>/create-message",create_message,name="create_message"),
]

jobs/urls.py
from django.urls import path

from .views import list_jobs,details_job

app_name = "jobs"

urlpatterns = [
    path('',list_jobs,name="list"),
    path('<int:pk>/',details_job,name='details')
]

interviews/models.py
import uuid

from django.db import models
from django.conf import settings


# Create your models here.

class Chat(models.Model):
    uuid = models.UUIDField(primary_key=True, editable=False)
    title = models.CharField(max_length=100, editable=False,verbose_name='Título')
    job = models.ForeignKey("jobs.Job", on_delete=models.CASCADE, related_name="chats")
    completed = models.BooleanField(default=False)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.uuid:
            self.uuid = uuid.uuid4()
            self.title = f"Chat {self.job.title} - {self.uuid}"
            super().save(*args, **kwargs)
            initial_prompt = settings.INITIAL_PROMPT_TEMPLATE
            initial_prompt = initial_prompt.replace("{job_title}", self.job.title)
            initial_prompt = initial_prompt.replace("{job_requirements}", self.job.requirements)
            initial_prompt = initial_prompt.replace("{job_responsibilities}", self.job.responsibilities)
            Message.objects.create(chat=self, role="system", content=initial_prompt)
        else:
            super().save(*args, **kwargs)

class Message(models.Model):
    ROLE_CHOICES = (
        ("system", "Sistema"),
        ("user", "Candidato"),
        ("assistant", "Ada")
    )

    chat = models.ForeignKey("interviews.Chat", on_delete=models.CASCADE, related_name="messages")
    role = models.CharField(max_length=9, choices=ROLE_CHOICES)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.role} - {self.chat.title}"
    
    def save(self, *args, **kwargs):
        if not self.pk and self.role != "assistant" and not self.chat.completed:
            super().save(*args, **kwargs)

            if self.role == "user" and self.chat.messages.filter(role="assistant").count() == 5:
                Message.objects.create(
                    chat=self.chat,
                    role="system",
                    content="Realize o feedback do candidato ao curso, esse feedback deve indicar quais os pontos positivos, os pontos negativos e o que deve ser melhorado, e de acordo com as respostas mensurar um porcentagem de aderência a vaga que vai de 0 a 100, e caso o candidato não tenha conhecimento em informatica basica, indicar o curo de introdução a informatica do senac. "
                )
                self.chat.completed = True
                self.chat.save()
            else:
                from .services import GptService
                service = GptService()
                Message.objects.create(
                    chat=self.chat,
                    role="assistant",
                    content=service.get_chat_completion(self.chat.messages.all())
                )
        else:
            super().save(*args, **kwargs)

jobs/models.py
from django.db import models

# Create your models here.

class Job(models.Model):
    LEVEL_CHOICES = (
        ('ba', 'Básico'),
        ('in', 'Intermediário'),
        ('av', 'Avançado'),
    )

    title = models.CharField(max_length=100,verbose_name='Título do curso')
    description = models.TextField(verbose_name='Descrição do curso')
    requirements = models.TextField(verbose_name='Pré-requisito do curso')
    responsibilities = models.TextField(verbose_name='Responsabilidades')
    level = models.CharField(max_length=2, choices=LEVEL_CHOICES, verbose_name='Nivel')
    skills = models.ManyToManyField("jobs.Skill", related_name="jobs",verbose_name='Skills necessárias')

    def __str__(self):
        return self.title
    
    def requirements_list(self):
        return self.requirements.split("\n")
    
    def responsibilities_list(self):
        return self.responsibilities.split("\n")


class Skill(models.Model):
    title = models.CharField(max_length=100, unique=True, blank=False, null=False)

    def __str__(self):
        return self.title
    

interviews/views.py
from django.http import HttpResponseNotAllowed
from django.shortcuts import render,get_object_or_404,redirect

from jobs.models import Job
from .models import Chat,Message

# Create your views here.

def create(request,job_pk):
    if request.method == "POST":
        job = get_object_or_404(Job,pk=job_pk)
        chat = Chat.objects.create(job=job)
        return redirect("interviews:details",uuid=chat.uuid)
    return HttpResponseNotAllowed(permitted_methods=("POST", ))

def details(request, uuid):
    chat = get_object_or_404(Chat,uuid=uuid)
    return render(
        request,
        "interviews/details.html",
        {
            "page_title": f"Entrevista para: {chat.job.title}",
            "chat":chat,
        }
    )

def create_message(request,chat_uuid):
    if request.method == "POST":
        chat = get_object_or_404(Chat,uuid=chat_uuid)
        answer = request.POST.get("answer")
        Message.objects.create(
            chat=chat,
            role="user",
            content=answer
        )
        return redirect("interviews:details", uuid=chat_uuid)
    return HttpResponseNotAllowed(permitted_methods=("POST", ))

jobs/views.py
from django.shortcuts import render,get_object_or_404
from .models import Job
# Create your views here.

def list_jobs(request):
    return render(
        request,
        "jobs/list.html",
        {
            "page_title": "Lista de cursos - Senac  ",
            "jobs": Job.objects.all()
        }
    )

def details_job(request,pk):
    job = get_object_or_404(Job,pk=pk)
    return render(
        request,
        "jobs/details.html",
        {
            "page_title": job.title,
            "job":job
        }
    )

interviews/templates/interviews/details.html
{% extends 'bases/base.html' %}

{% block 'body' %}

        <h1>{{page_title}}</h1>

    {% for message  in chat.messages.all %}
       {% if message.role != 'system' %}
            <div class="card mb-3">
                <div class="card-header d-flex">
                    {{message.get_role_display}}
                </div>
                <div class="card-body">
                    <p class="card-text">
                        {{message.content|linebreaksbr}}
                     </p>
                </div>
            </div>

       {% endif %}
    {% endfor %}

    <form action="{% url 'interviews:create_message' chat_uuid=chat.uuid %}" method="POST">
        {% csrf_token %}
        <div class="form-floating mb-2">
            <textarea 
            autofocus style="height: 150px;"
            class="form-control" 
            placeholder="Coloquei aqui sua resposta" 
            id="answer"
            name="answer"
            ></textarea>
            <label for="answer">Resposta</label>            
        </div>
        <button type="submit" class="btn btn-primary mb-4">Enviar</button>
    </form>

{% endblock %}

jobs/templates/jobs/details.html
{% extends 'bases/base.html' %}

{% block 'body' %}
    <section class="py-5 ">
        <h1>{{ page_title }} - {{ job.get_level_display }}</h1>
        <div>
            {% for skill in job.skills.all %}
                <span class="badge text-bg-primary">{{ skill.title }}</span>
             {% endfor %}
        </div>
        <h2 class="mt-3"> Descrição </h2>
        <p>{{job.description|linebreaksbr}}</p>

        <h2 class="mt-3"> Requisitos </h2>
        <ul>
            {% for requirement in job.requirements_list %}
                <li>{{requirement}}</li>

            {% endfor %}
        </ul>

        <h2 class="mt-3"> Responsabilidades </h2>
        <ul>
            {% for responsibilite in job.responsibilities_list %}
                <li>{{responsibilite}}</li>
            {% endfor %}
        </ul>

        <form action="{% url 'interviews:create' job_pk=job.pk %}" method="POST">
            {% csrf_token %}
            <button type="submit" class="btn btn-success"> Realizar teste de aptidão </button>
        </form>
    </section>
   

{% endblock %}  

jobs/templates/jobs/list.html
{% extends 'bases/base.html' %}

{% block 'body' %}
<section class="py-5">
    <div class="container">
        <h1>{{ page_title }}</h1>
        <div class="card-area mt-4 px-2">
            {% for job in jobs %}
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title fw-bolder">
                        {{job.title }}
                    </h5>
                    <h6 class="card-substitle mb-2 text-body secondary">
                        {{job.get_level_display}}
                    </h6>
                    <p class="card-text">
                        {% for skill in job.skills.all %}
                            <span class="badge text-bg-primary"> {{ skill.title }} </span>
                            
                        {% endfor %}
                    </p>
                    <div class="links">
                        <a href="{% url 'jobs:details' pk=job.pk %}" class="mt-4">Detalhes</a>
                    </div>

                </div>

            </div>

            {% endfor %}
        </div>
    </div>   

</section>
{% endblock %}

templates/bases/base.html
{% load static %}
<!doctype html>
<html lang="pt-br">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Exame de aptidão - Senac</title>
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <style>
    .card-area{
        display: grid;
        grid-template-columns: repeat(auto-fit, minmax(250px,1fr));
        gap: 30px;
        }
    .card{
        max-height: 300px;
        overflow: hidden;
        }
    .card-body{
        display: flex;
        flex-direction: column;
        }
    .card-body .links{
        margin-top: auto;
        }
    .card h5{
        overflow: hidden;
        display: -webkit-box;
        -webkit-line-clamp: 3;
        line-clamp: 3;
        -webkit-box-orient: vertical;
        }
    </style>
    </head>
  <body>
    <nav class="navbar bg-dark" data-bs-theme="dark">
        <div class="container">
            <a href="{% url 'jobs:list' %}" class="navbar-brand">
                SkilAi - Sistema de auxilio em definição de carrreiras 
            </a>            
        </div>
    </nav>

    <main>
        <section class="py-5">
            <div class="container">
                {% block 'body' %}
                
                {% endblock %}
            </div>
        </section>
    </main>

    <footer class="bg-dark fixed-bottom">
        <div class="container">
            <div><p class="text-white text-center m-0 py-3"> Senac - Maranhão | Rua do Passeio nº 495 - Centro - São Luís - MA </p></div>
            <div><p class="text-white text-center m-0 py-3"> 98 3198-1515 | ouvidoria@ma.senac.br </p></div>
        </div>
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.min.js" integrity="sha384-Rx+T1VzGupg4BHQYs2gCW9It+akI2MM/mndMCy36UVfodzcJcF0GGLxZIzObiEfa" crossorigin="anonymous"></script>
  </body>
</html>